### ISSUE TITLE
javascript cdns needs to be https://

### ISSUE THREAD

**Issue by krisrs1128** [krisrs1128/OpioidAtlas#2]
The images are failing to load sometimes because we're using http:// in the CDNS. E.g., whenever we load d3, we should make sure the prefix is https://.

**Comment by stamang** [comment]
Unless you prefer to do it, I can update the links.

-Suzanne

**Comment by krisrs1128** [comment]
Oh, don't worry about it, I can take care of it. I just wanted to make sure I don't forget.

**Comment by stamang** [comment]
Sounds good =)

Whenever I point to the CDN instead of maintaining/referencing local site’s resources I feel like a parasite...  but we don’t have much activity, and  unless you feel otherwise, I feel an appropriate use of the CDN.

-Suzanne

**Comment by krisrs1128** [comment]
Ah, I'd never even thought of that before. But I think this is fine for now, if we do start getting more traffic we can always update the references.
